### ISSUE TITLE
No audio mojave

### ISSUE THREAD

**Issue by BigD1979666** [nguyentrucxinh/ASUS-VivoBook-X510UQR-Hackintosh#2]
Hey sir. thanks for this great stuff. Most works on my vivobook S405UA( I avoided al your dsdt stuff save for battery because it worked). 

I cant get audio working in mojave. Are you only using alc, lilu, and codec? Did you have to change layout between osx releases?

**Comment by nguyentrucxinh** [comment]
Sorry, bro. Your machine is different from me a lot. Maybe this guy can help you, try to take a look https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh
Good luck!
